### ISSUE TITLE
ElasticSearchSearchEngine error

### ISSUE THREAD

**Issue by Ritwik6271** [K-Phoen/backstage-plugin-confluence#151]
I'm new to Backstage. I tried installing this plugin but I'm not sure if I did anything wrong. I replaced the existing default async function createPlugin. But now I'm getting error when running it in local

```
2023-02-01T11:52:43.015Z techdocs info Creating Local publisher for TechDocs type=plugin
Backend failed to start up ReferenceError: ElasticSearchSearchEngine is not defined
    at createPlugin (webpack-internal:///./src/plugins/search.ts:74:26)
    at main (webpack-internal:///./src/index.ts:101:95)
```

**Comment by K-Phoen** [comment]
It looks like you're trying to use the `ElasticSearchSearchEngine` class without having importing it first :)
