### ISSUE TITLE
Issue with indexing

### ISSUE THREAD

**Issue by mist3r3** [K-Phoen/backstage-plugin-confluence#180]
Hi, I get this issue while trying to run the plugin.
Somehow it cannot index it. Bu I see not specific error in the backend.

I'm not even sure which rest api it tries to run...

{
  "error": {
    "name": "MissingIndexError",
    "message": "Missing index for confluence. This could be because the index hasn't been created yet or there was a problem during index creation.",
    "stack": "MissingIndexError: Missing index for confluence. This could be because the index hasn't been created yet or there was a problem during index creation.\n    at LunrSearchEngine.query (/Users/em/backstage/backstage/node_modules/@backstage/plugin-search-backend-node/dist/index.cjs.js:329:13)\n    at /Users/em/backstage/backstage/node_modules/@backstage/plugin-search-backend/dist/cjs/router-8d1d26a0.cjs.js:250:67\n    at handleReturn (/Users/em/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /Users/em/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at handleReturn (/Users/em/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /Users/em/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/Users/em/backstage/backstage/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/em/backstage/backstage/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/em/backstage/backstage/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/em/backstage/backstage/node_modules/express/lib/router/layer.js:95:5)"
  },
  "request": {
    "method": "GET",
    "url": "/query?term=authz&types%5B0%5D=confluence"
  },
  "response": {
    "statusCode": 500
  }
}

**Comment by mist3r3** [comment]
The issue is that it took some time to index those documentations
